### ISSUE TITLE
Implement support for NAN 2.0

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire-js#6]

**Comment by Globik** [comment]
Excuse me, how to implement gcc into cmakelists.txt for cmake-js? I am on windows 7, vs 2010.

**Comment by unbornchikken** [comment]
Hi. GCC on Windows is not yet supported compiler for developing native addons. I have plans to support it in CMake.js. Please, upvote the issue there: https://github.com/unbornchikken/cmake-js/issues/17

**Comment by unbornchikken** [comment]
0.15+ is compatible with io.js 3.2+
